# Optional override for base packages installed by the role
apt_default_packages:
  - acl
  - aptitude
  - apt-transport-https
  - curl
  - dnsutils
  - gnupg2
  - haveged
  - locate
  - lsof
  - ncdu
  - net-tools
  - parted
  - psmisc
  - python3
  - python3-apt
  - python3-dev
  - python3-passlib
  - rsync
  - tcpdump
  - tmux
  - telnet
  - unattended-upgrades
  - vim
  - htop
